### ISSUE TITLE
NeMo compatibilaty with first RAG implementation 

### ISSUE THREAD

**Issue by ACraig7** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#96]
@itsnotmik @smrchanda877 @Jagadeesh-ajjada 
Was working on the NeMo Curator and Guardrails installation wiki and tried to get NeMo to work with the main branch as of 10/7/2024 at 6:00 P.M. The image builds fine but it seems there is some infinite recursion going on in `rag.py`. The docker error when running the image is as follows: 
```
2024-10-07 18:42:30 Traceback (most recent call last):
2024-10-07 18:42:30   File "/app/app.py", line 4, in <module>
2024-10-07 18:42:30     from RAG import *
2024-10-07 18:42:30   File "/app/RAG.py", line 6, in <module>
2024-10-07 18:42:30     from langchain_mistralai.chat_models import ChatMistralAI
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_mistralai/__init__.py", line 1, in <module>
2024-10-07 18:42:30     from langchain_mistralai.chat_models import ChatMistralAI
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_mistralai/chat_models.py", line 361, in <module>
2024-10-07 18:42:30     class ChatMistralAI(BaseChatModel):
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/main.py", line 221, in __new__
2024-10-07 18:42:30     inferred = ModelField.infer(
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 504, in infer
2024-10-07 18:42:30     return cls(
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 434, in __init__
2024-10-07 18:42:30     self.prepare()
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 544, in prepare
2024-10-07 18:42:30     self._set_default_and_type()
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 568, in _set_default_and_type
2024-10-07 18:42:30     default_value = self.get_default()
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 437, in get_default
2024-10-07 18:42:30     return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/utils.py", line 694, in smart_deepcopy
2024-10-07 18:42:30     return deepcopy(obj)  # slowest way when we actually might need a deepcopy
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/copy.py", line 172, in deepcopy
2024-10-07 18:42:30     y = _reconstruct(x, memo, *rv)
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/copy.py", line 272, in _reconstruct
2024-10-07 18:42:30     if hasattr(y, '__setstate__'):
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/_internal/_decorators.py", line 206, in __getattr__
2024-10-07 18:42:30     return getattr(self.wrapped, __name)
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/_internal/_decorators.py", line 206, in __getattr__
2024-10-07 18:42:30     return getattr(self.wrapped, __name)
2024-10-07 18:42:30   File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/_internal/_decorators.py", line 206, in __getattr__
2024-10-07 18:42:30     return getattr(self.wrapped, __name)
2024-10-07 18:42:30   [Previous line repeated 958 more times]
2024-10-07 18:42:30 RecursionError: maximum recursion depth exceeded
```

All I added to get the docker image to instal NeMo was:
* Two packages
     * `build-essential `
     *  `python3-dev `
```
RUN apt-get update && apt-get install -y \
	wget \
	bzip2 \
	ca-certificates \
	build-essential \
    python3-dev \
	&& rm -rf /var/lib/apt/lists/*
```
* Three pips:
     * `Cython` required for NeMo Curator
     * `nemo-curator`
     * ` nemoguardrails `
    
Since they are non mamba packages they are installed via this command in the Dockerfile:
```
# Install Python packages not on Mamba DB
RUN pip install -qU cython
RUN pip install -qU langchain_milvus langchain-cohere nemo-curator nemoguardrails
```
I pushed my current implementation of NeMo installation into the `NeMo` branch. Will continue to find a solution but let me know if you come up with anything.

**Comment by itsnotmik** [comment]
This bug is pretty crazy. I am confident that it is something to do with NeMoGuardrails. Ive tested different combinations of the 3 new pip installs and only when NeMoGuardrails is installed does it have an error. Everytime guardrails is installed the docker fails to run.

Running it on my system got the same error where the code enters the line `from langchain-mistralai import ChatMistral`

I suspected that it was an error with the langchain-mistralai library and guardrails, so I removed the langchain-mistralai import and replaced it with the langcahin-cohere import. This produced a new error 
```
Traceback (most recent call last):
  File "/app/app.py", line 4, in <module>
    from RAG import *
  File "/app/RAG.py", line 7, in <module>
    from langchain_cohere import ChatCohere
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_cohere/__init__.py", line 1, in <
module>
    from langchain_cohere.chains.summarize.summarize_chain import load_summarize_chain
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_cohere/chains/summarize/summarize
_chain.py", line 18, in <module>
    from langchain_cohere.chat_models import ChatCohere
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_cohere/chat_models.py", line 58, 
in <module>
    from langchain_cohere.llms import BaseCohere
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_cohere/llms.py", line 56, in <mod
ule>
    class BaseCohere(Serializable):
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/main.py", line 197, in __new__ 
    fields[ann_name] = ModelField.infer(
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 504, in infer 
    return cls(
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 434, in __init
__
    self.prepare()
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 555, in prepar
e
    self.populate_validators()
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/fields.py", line 829, in popula
te_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pydantic/v1/validators.py", line 765, in fi
nd_validators
    raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
RuntimeError: no validator found for <class 'pydantic.types.SecretStr'>, see `arbitrary_types_allowed` in Conf
ig
```

The only thing that we are not doing is setting the env variable for CC and CXX as described [here](https://docs.nvidia.com/nemo/guardrails/getting_started/installation-guide.html#prerequisites). I am unsure if this is a solution and haven't been able to test it

**Comment by ACraig7** [comment]
I found a fix that works for me. I added `pydantic==2.5.2` to `requirements.txt` and the error went away and it runs fine. Test it when you have a chance and let me know if it works for you. I found the solution by adding `pydantic==1.0` at first and it would not build the image and the console log told me that MistralAI needs Pydantic version 2.5.2 or greater.

**Comment by ACraig7** [comment]
Issue resolved
